// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF6odhWIni5Es9VvNVFjaFFCd_BIpBecY',
    appId: '1:911462287027:web:6a5a59f2a56fd0d80112c6',
    messagingSenderId: '911462287027',
    projectId: 'wechat-4c1be',
    authDomain: 'wechat-4c1be.firebaseapp.com',
    storageBucket: 'wechat-4c1be.firebasestorage.app',
    measurementId: 'G-KTRJ27ZH04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3-4L-sMyoR_pFSqmxdqSk4806mM2SZlg',
    appId: '1:911462287027:android:16c0922f5086f1e80112c6',
    messagingSenderId: '911462287027',
    projectId: 'wechat-4c1be',
    storageBucket: 'wechat-4c1be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExKxqIfTGIy9ZmiceZJb4hmsAFaAG4A4',
    appId: '1:911462287027:ios:fe6e4270cc3bb7ea0112c6',
    messagingSenderId: '911462287027',
    projectId: 'wechat-4c1be',
    storageBucket: 'wechat-4c1be.firebasestorage.app',
    iosBundleId: 'com.example.weChat',
  );

}